-- upgrade 1.20: domain scan (Active Directory computers + remote inventory)
CREATE TABLE IF NOT EXISTS domain_scan_runs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    started_by INT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'running',
    total INT NOT NULL DEFAULT 0,
    done INT NOT NULL DEFAULT 0,
    online INT NOT NULL DEFAULT 0,
    offline INT NOT NULL DEFAULT 0,
    failed INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS domain_scan_queue (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id INT UNSIGNED NOT NULL,
    asset_id INT UNSIGNED NULL,
    hostname VARCHAR(190) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    online TINYINT(1) NOT NULL DEFAULT 0,
    message VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY run_status (run_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE asset_profiles
    ADD COLUMN IF NOT EXISTS ad_dn VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS ad_os VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS ad_os_version VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS ad_last_logon DATETIME NULL,
    ADD COLUMN IF NOT EXISTS ad_last_seen DATETIME NULL,
    ADD COLUMN IF NOT EXISTS ad_scanned_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS ad_online TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ad_description VARCHAR(255) NULL;
