-- Upgrade 1.13: فرم شناسنامه رایانه، هم‌ساخت با فرم برنامه Inventory (Admin Yar)
-- فقط جدول asset_profiles و چند ستون خلاصه در assets

ALTER TABLE assets
    ADD COLUMN record_number VARCHAR(100) NULL AFTER asset_tag,
    ADD COLUMN computer_type VARCHAR(100) NULL AFTER model,
    ADD COLUMN plaque_number VARCHAR(100) NULL AFTER seal_number,
    ADD COLUMN person_number VARCHAR(100) NULL AFTER employee_number,
    ADD COLUMN city VARCHAR(100) NULL AFTER person_number;

CREATE TABLE IF NOT EXISTS asset_profiles (
    asset_id INT UNSIGNED NOT NULL PRIMARY KEY,
    record_number VARCHAR(100) NULL,
    registrar_name VARCHAR(190) NULL,
    registry_date DATETIME NULL,
    org_name VARCHAR(190) NULL,
    part_name VARCHAR(190) NULL,
    unit_name VARCHAR(190) NULL,
    user_name VARCHAR(190) NULL,
    computer_type VARCHAR(100) NULL,
    user_login VARCHAR(190) NULL,
    work_group VARCHAR(190) NULL,
    city VARCHAR(100) NULL,
    owner_full_name VARCHAR(190) NULL,
    education VARCHAR(190) NULL,
    phone VARCHAR(80) NULL,
    degree VARCHAR(190) NULL,
    skill_level VARCHAR(190) NULL,
    personnel_number VARCHAR(100) NULL,
    training_skills TEXT NULL,
    secure_info TEXT NULL,
    unit_software TEXT NULL,
    os_name VARCHAR(255) NULL,
    hostname VARCHAR(190) NULL,
    windows_serial VARCHAR(190) NULL,
    os_version VARCHAR(100) NULL,
    os_install_path VARCHAR(255) NULL,
    user_count VARCHAR(40) NULL,
    os_install_date DATETIME NULL,
    disk1_model VARCHAR(190) NULL,
    disk1_capacity VARCHAR(60) NULL,
    disk1_serial VARCHAR(190) NULL,
    disk2_model VARCHAR(190) NULL,
    disk2_capacity VARCHAR(60) NULL,
    disk2_serial VARCHAR(190) NULL,
    motherboard_model VARCHAR(190) NULL,
    motherboard_product VARCHAR(190) NULL,
    motherboard_serial VARCHAR(190) NULL,
    cpu_model VARCHAR(190) NULL,
    cpu_serial VARCHAR(190) NULL,
    cpu_cores VARCHAR(40) NULL,
    ram1 VARCHAR(190) NULL,
    ram2 VARCHAR(190) NULL,
    ram_total VARCHAR(60) NULL,
    gpu1_model VARCHAR(190) NULL,
    gpu1_memory VARCHAR(60) NULL,
    gpu2_model VARCHAR(190) NULL,
    gpu2_memory VARCHAR(60) NULL,
    audio VARCHAR(190) NULL,
    ip_address VARCHAR(100) NULL,
    mac_address VARCHAR(100) NULL,
    gateway VARCHAR(100) NULL,
    netcard VARCHAR(190) NULL,
    modem VARCHAR(190) NULL,
    net_node VARCHAR(100) NULL,
    connected_internet TINYINT(1) NOT NULL DEFAULT 0,
    connected_network TINYINT(1) NOT NULL DEFAULT 0,
    lock_usb TINYINT(1) NOT NULL DEFAULT 0,
    lock_case TINYINT(1) NOT NULL DEFAULT 0,
    lock_cd_dvd TINYINT(1) NOT NULL DEFAULT 0,
    monitor_model VARCHAR(190) NULL,
    monitor_serial VARCHAR(190) NULL,
    printer_model VARCHAR(190) NULL,
    printer_type VARCHAR(100) NULL,
    printer_serial VARCHAR(190) NULL,
    scanner_model VARCHAR(190) NULL,
    scanner_serial VARCHAR(190) NULL,
    keyboard_model VARCHAR(190) NULL,
    mouse_model VARCHAR(190) NULL,
    barcode_reader VARCHAR(190) NULL,
    antivirus VARCHAR(255) NULL,
    power_model VARCHAR(190) NULL,
    case_model VARCHAR(190) NULL,
    case_asset_number VARCHAR(100) NULL,
    plaque_type VARCHAR(100) NULL,
    plaque_serial VARCHAR(190) NULL,
    asset_number VARCHAR(100) NULL,
    updated_by INT UNSIGNED NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_asset_profile_asset FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE CASCADE,
    CONSTRAINT fk_asset_profile_user FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
